#!/bin/bash

set -e

if [ "$1" = configure ]; then

	INITSYS=$(ls -al /proc/1/exe | awk -F' ' '{print $NF}' | awk -F'/' '{print $NF}')
	ln -f -s /usr/share/shamarrconnect/shamarrconnect /usr/bin/shamarrconnect

	if [ "systemd" == "$INITSYS" ]; then

		if [ -e /etc/systemd/system/shamarrconnect.service ]; then
			rm /etc/systemd/system/shamarrconnect.service /usr/lib/systemd/system/shamarrconnect.service /usr/lib/systemd/user/shamarrconnect.service >/dev/null  2>&1
		fi
		mkdir -p /usr/lib/systemd/system/
		cp /usr/share/shamarrconnect/files/systemd/shamarrconnect.service /usr/lib/systemd/system/shamarrconnect.service
		# try fix error in Ubuntu 18.04
		# Failed to reload shamarrconnect.service: Unit shamarrconnect.service is not loaded properly: Exec format error.
		# /usr/lib/systemd/system/shamarrconnect.service:10: Executable path is not absolute: pkill -f "shamarrconnect --"
		if [ -e /usr/bin/pkill ]; then
			sed -i "s|pkill|/usr/bin/pkill|g" /usr/lib/systemd/system/shamarrconnect.service
		fi
		systemctl daemon-reload
		systemctl enable shamarrconnect
		systemctl start shamarrconnect
	fi
fi
